#!/bin/sh -e

sudo yum install -y git zlib-devel autoconf automake libtool python35 python35-pip
sudo python3 -m pip install xonsh[ptk]

git clone https://github.com/shellinabox/shellinabox.git
pushd shellinabox
autoreconf -i
./configure
make
sudo make install
popd

sudo useradd xonsh

sudo cp pam.conf /etc/pam.d/shellinabox
sudo cp upstart.conf /etc/init/shellinabox.conf
sudo cp xonshrc ~xonsh/.xonshrc
