#!/bin/sh -ex

BASE=`pwd`

# install xonsh
yum install -y git zlib-devel autoconf automake libtool python35 python35-pip
python3.5 -m pip install xonsh[ptk]

# install Let's Encrypt
git clone https://github.com/letsencrypt/letsencrypt
pushd letsencrypt
./letsencrypt-auto certonly --standalone \
    -d astro73.com -d hermit.astro73.com -d xon.sh \
    --agree-dev-preview --agree-tos --email scopatz@gmail.com
popd

# install shellinabox
git clone https://github.com/shellinabox/shellinabox.git
pushd shellinabox
autoreconf -i
./configure
make
make install
popd

# Some user setup
useradd xonsh
cp $BASE/pam.conf /etc/pam.d/shellinabox
cp $BASE/upstart.conf /etc/init/shellinabox.conf
cp $BASE/xonshrc ~xonsh/.xonshrc
